lint/src/util/structure.ts: fix TS2314
Fix error due to newer @typescript-eslint/eslint-plugin:

    error TS2314: Generic type 'RuleMetaData<MessageIds, Options>' requires 2 type argument(s).

    16 export type Meta = RuleMetaData<string>;